### ISSUE TITLE
Delete button is spelled wrong. it should be "Delete" also clicking the trash icon doesn't delete the json file. And while quitting godot is terminates godot as program did not respond.

### ISSUE THREAD

**Issue by RakibRyan** [folt-a/godot-idea-board#19]
I love your plugin.

**Comment by mrjuan1** [comment]
I have the same issue, the delete icon does nothing when I click on it.

**Comment by folt-a** [comment]
A possible reason why Godot crashes is that the "file node" reference in the Board is corrupt.

Click on the list to select and delete that item.
The file will open and crash.

In this case you can delete the json file directly.

valid files should now be able to be deleted from the list selection.

**Comment by mrjuan1** [comment]
This seems to be working for me now, thanks for the update!
