### ISSUE TITLE
shows this warning on godot 4.2

### ISSUE THREAD

**Issue by RakibRyan** [folt-a/godot-idea-board#20]
scene/resources/resource_format_text.cpp:448 - res://addons/godot-idea-board/file_node.tscn:4 - ext_resource, invalid UID: uid://b5qnqty0k1hsh - using text path instead: res://addons/godot-idea-board/icon/handle.svg
  scene/resources/resource_format_text.cpp:448 - res://addons/godot-idea-board/group_node.tscn:3 - ext_resource, invalid UID: uid://b5qnqty0k1hsh - using text path instead: res://addons/godot-idea-board/icon/handle.svg
  scene/resources/resource_format_text.cpp:448 - res://addons/godot-idea-board/comment_node.tscn:3 - ext_resource, invalid UID: uid://b5qnqty0k1hsh - using text path instead: res://addons/godot-idea-board/icon/handle.svg
  scene/resources/resource_format_text.cpp:448 - res://addons/godot-idea-board/link_node.tscn:3 - ext_resource, invalid UID: uid://b5qnqty0k1hsh - using text path instead: res://addons/godot-idea-board/icon/handle.svg
  scene/resources/resource_format_text.cpp:448 - res://addons/godot-idea-board/line_handle_node.tscn:3 - ext_resource, invalid UID: uid://b5qnqty0k1hsh - using text path instead: res://addons/godot-idea-board/icon/handle.svg
  scene/resources/resource_format_text.cpp:448 - res://addons/godot-idea-board/line_handle_node.tscn:10 - ext_resource, invalid UID: uid://b2jnsrl7naekt - using text path instead: res://addons/godot-idea-board/icon/normal_arrow.svg

**Comment by folt-a** [comment]
Thanks for your report.

I removed the UID information from the .tscn file.
Presumably this will prevent the warning from appearing.
