### ISSUE TITLE
Markdown bullet point lists not rendering

### ISSUE THREAD

**Issue by mrjuan1** [folt-a/godot-idea-board#21]
When adding a TxtDoc and typing markdown for bullet point lists (a `*` at the start of a line) and switching to markdown mode, the bullet point does not render. It just shows the `*` at the start of the line.

EDIT: Unless this is the intended behaviour?

**Comment by folt-a** [comment]
I changed the Markdown renderer.
Please check it.
https://github.com/daenvil/MarkdownLabel

**Comment by mrjuan1** [comment]
Looks great, thank you for the update!
