### ISSUE TITLE
godot 4.2 error 

### ISSUE THREAD

**Issue by RakibRyan** [folt-a/godot-idea-board#23]
modules/svg/image_loader_svg.cpp:75 - Condition "err" is true. Returning: Ref<Image>()
  It's not a reference to a valid Image object.
  modules/svg/image_loader_svg.cpp:75 - Condition "err" is true. Returning: Ref<Image>()
  It's not a reference to a valid Image object.
  modules/svg/image_loader_svg.cpp:75 - Condition "err" is true. Returning: Ref<Image>()
  It's not a reference to a valid Image object.
  modules/svg/image_loader_svg.cpp:75 - Condition "err" is true. Returning: Ref<Image>()
  It's not a reference to a valid Image object.
  modules/svg/image_loader_svg.cpp:75 - Condition "err" is true. Returning: Ref<Image>()
  It's not a reference to a valid Image object.
  res://addons/filesystem_drawer/plugin.gd:62 - Cannot call method 'has_setting' on a null value.
  res://addons/godot-idea-board/context_menu/line_handle_menu.gd:47 - Parse Error: Preload file "res://addons/godot-idea-board/icon/arrow_normal.svg" has no resource loaders (unrecognized file extension).
  modules/gdscript/gdscript.cpp:2726 - Failed to load script "res://addons/godot-idea-board/context_menu/line_handle_menu.gd" with error "Parse error". (User)
  res://addons/godot-idea-board/canvas_menu.gd:42 - Parse Error: Preload file "res://addons/godot-idea-board/icon/bg.svg" has no resource loaders (unrecognized file extension).
  modules/gdscript/gdscript.cpp:2726 - Failed to load script "res://addons/godot-idea-board/canvas_menu.gd" with error "Parse error". (User)
  res://addons/godot-idea-board/comment_node.gd:21 - Parse Error: Preload file "res://addons/godot-idea-board/icon/md.svg" has no resource loaders (unrecognized file extension).
  res://addons/godot-idea-board/comment_node.gd:22 - Parse Error: Preload file "res://addons/godot-idea-board/icon/b.svg" has no resource loaders (unrecognized file extension).
  res://addons/godot-idea-board/comment_node.gd:23 - Parse Error: Preload file "res://addons/godot-idea-board/icon/h1.svg" has no resource loaders (unrecognized file extension).
  res://addons/godot-idea-board/comment_node.gd:24 - Parse Error: Preload file "res://addons/godot-idea-board/icon/h2.svg" has no resource loaders (unrecognized file extension).
  modules/gdscript/gdscript.cpp:2726 - Failed to load script "res://addons/godot-idea-board/comment_node.gd" with error "Parse error". (User)
  res://addons/godot-idea-board/group_node.gd:21 - Parse Error: Preload file "res://addons/godot-idea-board/icon/tool_select.svg" has no resource loaders (unrecognized file extension).
  modules/gdscript/gdscript.cpp:2726 - Failed to load script "res://addons/godot-idea-board/group_node.gd" with error "Parse error". (User)
  res://addons/godot-idea-board/line_handle_node.gd:21 - Parse Error: Preload file "res://addons/godot-idea-board/icon/tool_select.svg" has no resource loaders (unrecognized file extension).
  modules/gdscript/gdscript.cpp:2726 - Failed to load script "res://addons/godot-idea-board/line_handle_node.gd" with error "Parse error". (User)
  No loader found for resource: res://addons/godot-idea-board/icon/handle.svg (expected type: Texture2D)
  No loader found for resource: res://addons/godot-idea-board/icon/handle.svg (expected type: Texture2D)
  No loader found for resource: res://addons/godot-idea-board/icon/handle.svg (expected type: Texture2D)
  No loader found for resource: res://addons/godot-idea-board/icon/handle.svg (expected type: Texture2D)
  No loader found for resource: res://addons/godot-idea-board/icon/handle.svg (expected type: Texture2D)
  No loader found for resource: res://addons/godot-idea-board/icon/normal_arrow.svg (expected type: Texture2D)
  res://addons/godot-idea-board/sekkei_graph.gd:92 - Invalid call. Nonexistent function 'init' in base 'VBoxContainer (canvas_menu.gd)'.
  res://addons/godot-idea-board/sekkei_graph.gd:92 - Invalid call. Nonexistent function 'init' in base 'VBoxContainer (canvas_menu.gd)'.
  res://addons/godot-idea-board/sekkei_graph.gd:92 - Invalid call. Nonexistent function 'init' in base 'VBoxContainer (canvas_menu.gd)'.

**Comment by folt-a** [comment]
Did you reload the project?

Immediately after the plugin is activated, you will not be able to load images or classes, so you will need to restart the editor.

**Comment by RakibRyan** [comment]
guess it needed reload
